//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KITAPDETAY
    {
        public int ID { get; set; }
        public Nullable<int> KITAP { get; set; }
        public string DETAY { get; set; }
    
        public virtual TBL_KITAP TBL_KITAP { get; set; }
    }
}
