//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BILDIRIM
    {
        public int ID { get; set; }
        public Nullable<int> UYE { get; set; }
        public string BASLIK { get; set; }
        public string ICERIK { get; set; }
        public Nullable<System.DateTime> GONDERIMTARIH { get; set; }
        public Nullable<bool> OKUNDU { get; set; }
    
        public virtual TBL_UYELER TBL_UYELER { get; set; }
    }
}
